### ISSUE TITLE
Infografia 

### ISSUE THREAD

**Issue by Arlet04** [SistemasTecTlaxiaco/actividad-10-infograf-a-de-calidad-de-software-Arlet04#1]
[Infografia Plan de Calidada Jeanette Arlet Salazar Nicolas.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-infograf-a-de-calidad-de-software-Arlet04/files/15461447/Infografia.Plan.de.Calidada.Jeanette.Arlet.Salazar.Nicolas.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
